### ISSUE TITLE
unknown type DPST-11-1

### ISSUE THREAD

**Issue by PhilippeRaven** [laurent-martin/ets-to-homeassistant#1]
Hi, I'm trying to convert to knxproj file to yaml file to import it in Home Assistant.
Currently I got the following error by running ./ets_to_hass.rb  myproj.knxproj :
`Traceback (most recent call last):
	6: from ./ets_to_hass.rb:127:in `<main>'
	5: from ./ets_to_hass.rb:127:in `new'
	4: from ./ets_to_hass.rb:24:in `initialize'
	3: from ./ets_to_hass.rb:24:in `each'
	2: from ./ets_to_hass.rb:27:in `block in initialize'
	1: from ./ets_to_hass.rb:27:in `each'
./ets_to_hass.rb:49:in `block (2 levels) in initialize': unknown type DPST-11-1  (RuntimeError)
`

I don't know if it's the only DPST type no handled I got in my proj, but at the moment I'm stuck with this.
Thanks !

**Comment by laurent-martin** [comment]
I have pushed a new version.

It is still limited, but by default it does not execute my specific code.

**Comment by PhilippeRaven** [comment]
Thanks, I'll try it !

**Comment by laurent-martin** [comment]
Latest vesion does not fail when unmanaged DPST is found.
DPST-11-1 is type "date", it is not listed here: https://www.home-assistant.io/integrations/knx/
