### ISSUE TITLE
./ets_to_hass.rb:29:in `initialize': undefined method `each' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by frankvandenhurk** [laurent-martin/ets-to-homeassistant#2]
Thank you for taking the time to build this utility. I'm sorry, but I'm not familiair with Ruby. I tried to run you tool, but got:

root@debian1:~/ets_to_hass# ./ets_to_hass.rb backup.knxproj
no specific code, set env var SPECIAL to load specific code
Traceback (most recent call last):
        2: from ./ets_to_hass.rb:152:in `<main>'
        1: from ./ets_to_hass.rb:152:in `new'
./ets_to_hass.rb:29:in `initialize': undefined method `each' for nil:NilClass (NoMethodError)

Any idea what I did wrong?

**Comment by laurent-martin** [comment]
there were major changes , so try again
