### ISSUE TITLE
don't filter special cars and numbers from GA Names

### ISSUE THREAD

**Issue by guptamp** [laurent-martin/ets-to-homeassistant#5]
Thanks for fixing the GA output!
I noticed that also some GA names are not complete and found it's to to the regex in "name_to_id" line 73.
I added "äöüÄÖÜß0-9" to the regex and that seems to work fine for me, but is maybe not the cleanest way to account for special letters.

**Comment by laurent-martin** [comment]
The newer version does not change names, but it requires to have building ojects
