### ISSUE TITLE
issue with when executing this script

### ISSUE THREAD

**Issue by cosmoricky** [laurent-martin/ets-to-homeassistant#6]
Hi,
first of all thank you very much for your effort and great work to realize this usecase to export/import KNX for HA.
But i'm facing to the problem when executing this script,i get always the failure  ./ets_to_hass.rb:207:in `block in <main>': undefined method `start_with?' for :process_space:Symbol (NoMethodError)
	from ./ets_to_hass.rb:207:in `select'
	from ./ets_to_hass.rb:207:in `<main>'
Im running the script on MAC OS 12.2 - and ruby 2.6.8p205 (2021-07-07 revision 67951). I installed gem install gem zip and gem xml-simple.
Would be reat if you can support me in that case

**Comment by laurent-martin** [comment]
Right, Symbol.start_with? was introduced in ruby 2.7.0 ...
I have modified so that it also works with earlier versions of Ruby.
