### ISSUE TITLE
Issues executing in OSX Terminal

### ISSUE THREAD

**Issue by jos89h** [laurent-martin/ets-to-homeassistant#7]
Hi, I have installed via terminal with no issue but i have an error when trying to execute the command if you can kindly help. Im not 100% I am following the procedure correctly. I did change "myexport.knxproj" to the local directory of my file.

> Fetching: bundler-2.3.15.gem (100%)
> Successfully installed bundler-2.3.15
> Parsing documentation for bundler-2.3.15
> Installing ri documentation for bundler-2.3.15
> Done installing documentation for bundler after 0 seconds
> 1 gem installed
> 192-168-1-43:~ josh$ ./ets_to_hass.rb homeass myexport.knxproj
> -bash: ./ets_to_hass.rb: No such file or directory

**Comment by laurent-martin** [comment]
You must first clone the repo, then `cd` to it, and do bundle install.

I have updated the manual.
