### ISSUE TITLE
Don´t understand debug results

### ISSUE THREAD

**Issue by BottoH** [laurent-martin/ets-to-homeassistant#9]
Hello,
thx for the script :) just trying to get the job done. I arragend my GA in ETS as functions like it is said in the "howto"-description, but I receive the following result.

Console:

```
c:\ets-to-homeassistant>ruby ets_to_hass.rb homeass myetsfile.knxproj
I, [2022-08-14T19:08:37.256853 #14804]  INFO -- : Using project reselage, address style: ThreeLevel
W, [2022-08-14T19:08:37.261842 #14804]  WARN -- : cannot parse datapoint : DPT-8, group is skipped
W, [2022-08-14T19:08:37.262253 #14804]  WARN -- : cannot parse datapoint : DPT-1, group is skipped
ets_to_hass.rb:53:in `block in dig_xml': ERROR: cannot find level Locations in xml (RuntimeError)
        from ets_to_hass.rb:51:in `each'
        from ets_to_hass.rb:51:in `dig_xml'
        from _ets_to_hass.rb:45:in_ `initialize'
        from ets_to_hass.rb:234:in `new'
        from ets_to_hass.rb:234:in `<main>'
```
I also wonder while I tried the samples where the export is saved? Do I have to stream this in an extra file like this (seems to work):
`c:\ets-to-homeassistant>ruby ets_to_hass.rb homeass myetsfile.knxproj >> export.txt`
Maybe a point that shoud be added to the "howto"-description.

Hope you can give a short support.
Regards bottoh

**Comment by laurent-martin** [comment]
The current version will not stop on this error.
